"""Tests for rovimen-scripts/rovimen_pusher.py — station-side push agent (Phase B).

Covers payload construction against the design §2.4 schema, the monotonic seq
envelope (§2.3, persisted across restarts), the opt-in key gate, config
resolution, and the buffering/retry/spool behaviour (§7).
"""

from __future__ import annotations

import json

import pytest

import rovimen_pusher as rp


# ── envelope + seq (§2.3) ──────────────────────────────────────────────────


class TestSeqCounter:
    def test_starts_at_zero_when_no_state(self, tmp_path):
        seq = rp.SeqCounter(state_path=tmp_path / "state.json")
        assert seq.current == 0
        assert seq.next() == 1
        assert seq.next() == 2

    def test_persists_across_restart(self, tmp_path):
        path = tmp_path / "state.json"
        seq = rp.SeqCounter(state_path=path)
        seq.next()
        seq.next()
        seq.next()
        # New instance reads the persisted value and keeps climbing.
        seq2 = rp.SeqCounter(state_path=path)
        assert seq2.current == 3
        assert seq2.next() == 4

    def test_corrupt_state_resets_to_zero(self, tmp_path):
        path = tmp_path / "state.json"
        path.write_text("not json {")
        seq = rp.SeqCounter(state_path=path)
        assert seq.current == 0
        assert seq.next() == 1

    def test_monotonic_strictly_increasing(self, tmp_path):
        seq = rp.SeqCounter(state_path=tmp_path / "state.json")
        vals = [seq.next() for _ in range(50)]
        assert vals == sorted(vals)
        assert len(set(vals)) == len(vals)


class TestEnvelope:
    def test_envelope_shape(self):
        env = rp.build_envelope(42, {"online": True}, sent_at="2026-07-01T00:00:00Z")
        assert env["seq"] == 42
        assert env["sent_at"] == "2026-07-01T00:00:00Z"
        assert env["agent_version"] == rp.AGENT_VERSION
        assert env["payload"] == {"online": True}

    def test_sent_at_autogenerated_rfc3339(self):
        env = rp.build_envelope(1, {})
        # RFC3339 UTC 'Z' form.
        assert env["sent_at"].endswith("Z")
        assert "T" in env["sent_at"]


# ── payload construction (§2.4) ────────────────────────────────────────────


class TestHeartbeatPayload:
    def test_projects_status_fields(self):
        status = {
            "online": True,
            "services": {"rms-cam0": True, "color-capture": True},
            "cameras": [{"code": "RO000M", "capturing": True}],
            "disk": {"used_pct": 61.2, "free_gb": 88.1},
            "storage": {"capt_dirs": 3},
            "extra_disks": [],
            "rms_running": True,
            "color_capture_running": True,
            "network_name": "ROVIMEN",
            "last_updated": "2026-07-01T00:00:00Z",  # extra field dropped
        }
        p = rp.build_heartbeat_payload(status)
        assert set(p) == {
            "online", "services", "cameras", "disk", "storage",
            "extra_disks", "rms_running", "color_capture_running", "network_name",
        }
        assert p["network_name"] == "ROVIMEN"
        assert "last_updated" not in p

    def test_defaults_when_fields_missing(self):
        p = rp.build_heartbeat_payload({})
        assert p["online"] is True
        assert p["services"] == {}
        assert p["cameras"] == []


class TestVitalsPayload:
    def test_projects_vitals_fields(self):
        vitals = {
            "cpu_pct": 34.5, "ram_pct": 41.0, "ram_used_mb": 3221,
            "ram_total_mb": 7861, "temp_c": 52.3, "total_cores": 6,
            "cores": [{"load_pct": 30.1, "freq_ghz": 2.9}],
            "disk_write_mbps": 1.8,
            "top_procs": [{"name": "python3", "cpu_pct": 22.0}],
        }
        p = rp.build_vitals_payload(vitals)
        assert p["cpu_pct"] == 34.5
        assert p["cores"][0]["freq_ghz"] == 2.9
        assert p["top_procs"][0]["name"] == "python3"


class TestDetectionsPayload:
    def test_wraps_rows_with_window(self):
        rows = [{"cam": "RO000M", "date": "20260630", "ff_file": "FF_x.fits",
                 "meteor_no": 1}]
        p = rp.build_detections_payload("20260617", rows)
        assert p["window_since"] == "20260617"
        assert p["detections"] == rows


class TestMediaPayload:
    def test_flattens_timelapses_endpoint(self):
        raw = {
            "RO000M": [
                {"date": "20260630", "filename": "a_timelapse.mp4",
                 "night_stack": "a_night_stack.webp"},
                {"date": "20260629", "filename": "b_timelapse.mp4",
                 "night_stack": None},
            ]
        }
        p = rp.build_media_payload(raw)
        assert p["clips"] == []
        assert len(p["timelapses"]) == 2
        assert p["timelapses"][0] == {
            "cam": "RO000M", "date": "20260630",
            "filename": "a_timelapse.mp4", "night_stack": "a_night_stack.webp",
        }
        # only the entry with a night_stack contributes a nightstack pointer
        assert len(p["nightstacks"]) == 1
        assert p["nightstacks"][0]["filename"] == "a_night_stack.webp"

    def test_empty_input(self):
        p = rp.build_media_payload({})
        assert p == {"timelapses": [], "nightstacks": [], "clips": []}

    def test_emits_clip_pointers(self):
        chunks = {
            ("RO000M", "20260630"): [
                {"filename": "RO000M_20260630_224107_color.mkv", "locked": True,
                 "lock_type": "detection", "meteor_time": "2026-06-30T22:41:07"},
                {"filename": "RO000M_20260630_230000_color.mkv", "locked": False},
            ],
        }
        p = rp.build_media_payload({}, chunks)
        assert len(p["clips"]) == 1
        clip = p["clips"][0]
        assert clip["cam"] == "RO000M"
        assert clip["date"] == "20260630"
        assert clip["filename"] == "RO000M_20260630_224107_color.mkv"
        assert clip["locked"] is True
        assert clip["meteor_time"] == "2026-06-30T22:41:07"
        assert clip["lock_type"] == "detection"

    def test_clip_pointers_skip_unlocked_and_missing_filename(self):
        chunks = {
            ("RO000N", "20260630"): [
                {"filename": "x_color.mkv", "locked": False},
                {"locked": True},  # no filename
            ],
        }
        assert rp.build_clip_pointers(chunks) == []


class TestLiveThumbPayload:
    def test_wraps_bytes_base64(self):
        import base64

        p = rp.build_live_thumb_payload(b"\x00webpbytes", "2026-06-30T22:41:07.120Z")
        assert p["content_type"] == "image/webp"
        assert p["ff_timestamp"] == "2026-06-30T22:41:07.120Z"
        assert base64.b64decode(p["data_b64"]) == b"\x00webpbytes"

    def test_null_timestamp_ok(self):
        p = rp.build_live_thumb_payload(b"abc", None)
        assert p["ff_timestamp"] is None


class TestLiveThumbIntervalResolution:
    def test_default(self, monkeypatch):
        monkeypatch.delenv("ROVIMEN_LIVE_THUMB_INTERVAL", raising=False)
        assert rp.resolve_live_thumb_interval({}) == rp.LIVE_THUMB_INTERVAL

    def test_env_wins_and_clamps(self, monkeypatch):
        monkeypatch.setenv("ROVIMEN_LIVE_THUMB_INTERVAL", "5")
        assert rp.resolve_live_thumb_interval({}) == 10  # clamped floor
        monkeypatch.setenv("ROVIMEN_LIVE_THUMB_INTERVAL", "9999")
        assert rp.resolve_live_thumb_interval({}) == 300  # clamped ceiling
        monkeypatch.setenv("ROVIMEN_LIVE_THUMB_INTERVAL", "60")
        assert rp.resolve_live_thumb_interval({}) == 60

    def test_config_push_value(self, monkeypatch):
        monkeypatch.delenv("ROVIMEN_LIVE_THUMB_INTERVAL", raising=False)
        assert rp.resolve_live_thumb_interval({"push": {"live_thumb_interval": 30}}) == 30

    def test_invalid_falls_back(self, monkeypatch):
        monkeypatch.setenv("ROVIMEN_LIVE_THUMB_INTERVAL", "not-a-number")
        assert rp.resolve_live_thumb_interval({}) == rp.LIVE_THUMB_INTERVAL


# ── config / identity resolution ───────────────────────────────────────────


class TestResolveIngestKey:
    def test_env_wins(self, monkeypatch, tmp_path):
        monkeypatch.setenv("ROVIMEN_INGEST_KEY", "rvmn_env_secret")
        assert rp.resolve_ingest_key(tmp_path / "nope.key") == "rvmn_env_secret"

    def test_reads_key_file_first_line(self, monkeypatch, tmp_path):
        monkeypatch.delenv("ROVIMEN_INGEST_KEY", raising=False)
        kp = tmp_path / "ingest.key"
        kp.write_text("\nrvmn_gmn0002_abc\n")
        assert rp.resolve_ingest_key(kp) == "rvmn_gmn0002_abc"

    def test_missing_key_returns_none(self, monkeypatch, tmp_path):
        monkeypatch.delenv("ROVIMEN_INGEST_KEY", raising=False)
        assert rp.resolve_ingest_key(tmp_path / "absent.key") is None


class TestResolveHostKey:
    def test_env_wins(self, monkeypatch):
        monkeypatch.setenv("ROVIMEN_HOST_KEY", "gmnro02")
        assert rp.resolve_host_key({"host_key": "other"}) == "gmnro02"

    def test_config_host_key(self, monkeypatch):
        monkeypatch.delenv("ROVIMEN_HOST_KEY", raising=False)
        assert rp.resolve_host_key({"host_key": "gmn0002"}) == "gmn0002"

    def test_nested_push_host_key(self, monkeypatch):
        monkeypatch.delenv("ROVIMEN_HOST_KEY", raising=False)
        assert rp.resolve_host_key({"push": {"host_key": "gmnro10"}}) == "gmnro10"

    def test_none_when_undeterminable(self, monkeypatch):
        monkeypatch.delenv("ROVIMEN_HOST_KEY", raising=False)
        assert rp.resolve_host_key({}) is None


class TestResolveBaseUrl:
    def test_env_wins_and_strips_slash(self, monkeypatch):
        monkeypatch.setenv("ROVIMEN_INGEST_BASE_URL", "https://vps.example/")
        assert rp.resolve_base_url({}) == "https://vps.example"

    def test_derives_from_vps_host(self, monkeypatch):
        monkeypatch.delenv("ROVIMEN_INGEST_BASE_URL", raising=False)
        assert rp.resolve_base_url({"vps_host": "100.64.0.1"}) == \
            "https://100.64.0.1"

    def test_push_config_base(self, monkeypatch):
        monkeypatch.delenv("ROVIMEN_INGEST_BASE_URL", raising=False)
        cfg = {"push": {"ingest_base_url": "https://ingest.rovimen.org"}}
        assert rp.resolve_base_url(cfg) == "https://ingest.rovimen.org"

    def test_none_when_undeterminable(self, monkeypatch):
        monkeypatch.delenv("ROVIMEN_INGEST_BASE_URL", raising=False)
        assert rp.resolve_base_url({}) is None


# ── backoff ─────────────────────────────────────────────────────────────────


class TestBackoff:
    def test_grows_and_caps(self):
        prev_cap = rp.backoff_delay(0)
        assert 0 < prev_cap <= rp.BASE_BACKOFF
        big = rp.backoff_delay(20)
        assert big <= rp.MAX_BACKOFF


# ── spool buffering (§7) ────────────────────────────────────────────────────


class TestSpool:
    def test_add_and_pending(self, tmp_path):
        sp = rp.Spool(path=tmp_path / "spool.db")
        sp.add("detections", "detections", {"seq": 1})
        pending = sp.pending()
        assert len(pending) == 1
        _, endpoint, body = pending[0]
        assert endpoint == "detections"
        assert body == {"seq": 1}
        sp.close()

    def test_heartbeat_coalesces_to_latest(self, tmp_path):
        sp = rp.Spool(path=tmp_path / "spool.db")
        sp.add("heartbeat", "heartbeat", {"seq": 1})
        sp.add("heartbeat", "heartbeat", {"seq": 2})
        sp.add("heartbeat", "heartbeat", {"seq": 3})
        pending = sp.pending()
        assert len(pending) == 1
        assert pending[0][2] == {"seq": 3}
        sp.close()

    def test_detections_do_not_coalesce(self, tmp_path):
        sp = rp.Spool(path=tmp_path / "spool.db")
        sp.add("detections", "detections", {"seq": 1})
        sp.add("detections", "detections", {"seq": 2})
        assert sp.count() == 2
        sp.close()

    def test_remove(self, tmp_path):
        sp = rp.Spool(path=tmp_path / "spool.db")
        sp.add("vitals", "vitals", {"seq": 1})
        row_id = sp.pending()[0][0]
        sp.remove(row_id)
        assert sp.count() == 0
        sp.close()

    def test_bounded_size(self, tmp_path, monkeypatch):
        monkeypatch.setattr(rp, "SPOOL_MAX_ROWS", 5)
        sp = rp.Spool(path=tmp_path / "spool.db")
        for i in range(20):
            sp.add("detections", "detections", {"seq": i})
        assert sp.count() == 5
        # kept the newest
        seqs = sorted(b["seq"] for _, _, b in sp.pending())
        assert seqs == [15, 16, 17, 18, 19]
        sp.close()


# ── publisher send/retry/spool integration ─────────────────────────────────


class _FakePost:
    """Records POST calls and returns a scripted sequence of PostResults."""

    def __init__(self, results):
        self.results = list(results)
        self.calls = []

    def __call__(self, url, key, body, timeout=None):
        self.calls.append((url, key, body))
        if self.results:
            return self.results.pop(0)
        return rp.PostResult(ok=True, status=200)


def _make_publisher(tmp_path):
    seq = rp.SeqCounter(state_path=tmp_path / "state.json")
    spool = rp.Spool(path=tmp_path / "spool.db")
    pub = rp.Publisher("https://vps.example", "gmn0002", "rvmn_key", seq, spool)
    return pub, spool


class TestPublisherSend:
    def test_success_does_not_spool(self, tmp_path, monkeypatch):
        pub, spool = _make_publisher(tmp_path)
        fake = _FakePost([rp.PostResult(ok=True, status=200)])
        monkeypatch.setattr(rp, "post_json", fake)
        ok = pub._send("heartbeat", "heartbeat", {"online": True})
        assert ok is True
        assert spool.count() == 0
        # URL is the ingest path with host_key.
        assert fake.calls[0][0] == \
            "https://vps.example/api/ingest/v1/gmn0002/heartbeat"
        assert fake.calls[0][1] == "rvmn_key"
        spool.close()

    def test_failure_spools_non_detections(self, tmp_path, monkeypatch):
        pub, spool = _make_publisher(tmp_path)
        fake = _FakePost([rp.PostResult(ok=False, status=500)])
        monkeypatch.setattr(rp, "post_json", fake)
        ok = pub._send("vitals", "vitals", {"cpu_pct": 1})
        assert ok is False
        assert spool.count() == 1
        spool.close()

    def test_failure_does_not_spool_detections(self, tmp_path, monkeypatch):
        pub, spool = _make_publisher(tmp_path)
        fake = _FakePost([rp.PostResult(ok=False, status=500)])
        monkeypatch.setattr(rp, "post_json", fake)
        ok = pub._send("detections", "detections", {"detections": []})
        assert ok is False
        assert spool.count() == 0
        spool.close()

    def test_seq_increments_per_send(self, tmp_path, monkeypatch):
        pub, spool = _make_publisher(tmp_path)
        fake = _FakePost([rp.PostResult(ok=True), rp.PostResult(ok=True)])
        monkeypatch.setattr(rp, "post_json", fake)
        pub._send("heartbeat", "heartbeat", {})
        pub._send("vitals", "vitals", {})
        seqs = [c[2]["seq"] for c in fake.calls]
        assert seqs == [1, 2]
        spool.close()

    def test_drain_spool_flushes_then_removes(self, tmp_path, monkeypatch):
        pub, spool = _make_publisher(tmp_path)
        spool.add("vitals", "vitals", rp.build_envelope(1, {"cpu_pct": 1}))
        spool.add("media", "media", rp.build_envelope(2, {}))
        fake = _FakePost([rp.PostResult(ok=True), rp.PostResult(ok=True)])
        monkeypatch.setattr(rp, "post_json", fake)
        pub.drain_spool()
        assert spool.count() == 0
        assert len(fake.calls) == 2
        spool.close()

    def test_drain_spool_stops_on_failure(self, tmp_path, monkeypatch):
        pub, spool = _make_publisher(tmp_path)
        spool.add("vitals", "vitals", rp.build_envelope(1, {}))
        spool.add("media", "media", rp.build_envelope(2, {}))
        # first fails -> stop, both remain buffered
        fake = _FakePost([rp.PostResult(ok=False, status=503)])
        monkeypatch.setattr(rp, "post_json", fake)
        pub.drain_spool()
        assert spool.count() == 2
        assert len(fake.calls) == 1
        spool.close()


class TestPublisherPushHelpers:
    def test_push_detections_empty_is_success_no_post(self, tmp_path, monkeypatch):
        pub, spool = _make_publisher(tmp_path)
        monkeypatch.setattr(rp, "fetch_detections", lambda since: [])
        fake = _FakePost([])
        monkeypatch.setattr(rp, "post_json", fake)
        assert pub.push_detections() is True
        assert fake.calls == []
        spool.close()

    def test_push_heartbeat_returns_false_when_local_api_down(self, tmp_path, monkeypatch):
        pub, spool = _make_publisher(tmp_path)
        monkeypatch.setattr(rp, "fetch_status", lambda: None)
        assert pub.push_heartbeat() is False
        spool.close()


# ── command worker (§3) — verify, dispatch, ack, fail-closed ────────────────


def _mint_keypair(tmp_path):
    """Return (pubkey_raw, sign_fn) using the server signer for parity."""
    import sys
    sys.path.insert(0, "dashboard")
    import command_signing
    priv = tmp_path / "priv.pem"
    pub = tmp_path / "pub.pem"
    command_signing.generate_keypair(priv, pub)
    import command_verify
    pubkey_raw = command_verify.load_public_key_raw(pub)
    key = command_signing.load_private_key(priv)

    def sign(cmd: dict, station: str) -> str:
        msg = command_signing.canonical_message(
            id=cmd["id"], station=station, type=cmd["type"], args=cmd.get("args", {}),
            issued_at=cmd["issued_at"], not_after=cmd["not_after"],
        )
        return command_signing.sign(msg, key)

    return pubkey_raw, sign


def _future(minutes=5):
    from datetime import datetime, timedelta, timezone
    return (datetime.now(timezone.utc) + timedelta(minutes=minutes)).strftime("%Y-%m-%dT%H:%M:%SZ")


def _past(minutes=5):
    from datetime import datetime, timedelta, timezone
    return (datetime.now(timezone.utc) - timedelta(minutes=minutes)).strftime("%Y-%m-%dT%H:%M:%SZ")


class TestCommandWorker:
    def _worker(self, tmp_path, monkeypatch):
        pubkey_raw, sign = _mint_keypair(tmp_path)
        stop = __import__("threading").Event()
        w = rp.CommandWorker("https://vps.example", "gmn0002", "rvmn_k", pubkey_raw, stop)
        acks: list[tuple[str, bool, str]] = []
        posts: list[tuple[str, dict | None]] = []
        monkeypatch.setattr(w, "_ack", lambda cid, ok, detail: acks.append((cid, ok, detail)))
        monkeypatch.setattr(rp, "_local_post", lambda path, body=None, timeout=60: posts.append((path, body)) or (True, "ok"))
        return w, sign, acks, posts

    def test_valid_signed_command_dispatches(self, tmp_path, monkeypatch):
        w, sign, acks, posts = self._worker(tmp_path, monkeypatch)
        cmd = {"id": "cmd_1", "type": "restart_service", "args": {"service": "rms-cam0"},
               "issued_at": _future(-1), "not_after": _future()}
        cmd["sig"] = sign(cmd, "gmn0002")
        w.handle(cmd)
        assert posts == [("/api/restart/rms-cam0", None)]
        assert acks[-1][1] is True

    def test_tampered_command_refused(self, tmp_path, monkeypatch):
        w, sign, acks, posts = self._worker(tmp_path, monkeypatch)
        cmd = {"id": "cmd_2", "type": "reboot", "args": {},
               "issued_at": _future(-1), "not_after": _future()}
        cmd["sig"] = sign(cmd, "gmn0002")
        cmd["type"] = "restart_service"  # tamper after signing
        cmd["args"] = {"service": "evil"}
        w.handle(cmd)
        assert posts == []                       # never dispatched
        assert acks[-1][1] is False
        assert "signature_invalid" in acks[-1][2]

    def test_expired_command_refused(self, tmp_path, monkeypatch):
        w, sign, acks, posts = self._worker(tmp_path, monkeypatch)
        cmd = {"id": "cmd_3", "type": "reboot", "args": {},
               "issued_at": _past(10), "not_after": _past()}
        cmd["sig"] = sign(cmd, "gmn0002")
        w.handle(cmd)
        assert posts == []
        assert acks[-1][1] is False
        assert "expired" in acks[-1][2]

    def test_disallowed_type_refused_even_if_signed(self, tmp_path, monkeypatch):
        w, sign, acks, posts = self._worker(tmp_path, monkeypatch)
        cmd = {"id": "cmd_4", "type": "exec", "args": {"cmd": "rm -rf /"},
               "issued_at": _future(-1), "not_after": _future()}
        cmd["sig"] = sign(cmd, "gmn0002")
        w.handle(cmd)
        assert posts == []
        assert acks[-1][1] is False
        assert "disallowed_type" in acks[-1][2]

    def test_wrong_station_signature_refused(self, tmp_path, monkeypatch):
        """A command signed for a different station must not verify here."""
        w, sign, acks, posts = self._worker(tmp_path, monkeypatch)
        cmd = {"id": "cmd_5", "type": "reboot", "args": {},
               "issued_at": _future(-1), "not_after": _future()}
        cmd["sig"] = sign(cmd, "gmnro10")   # signed for another station
        w.handle(cmd)
        assert posts == []
        assert acks[-1][1] is False

    def test_lock_clip_dispatch(self, tmp_path, monkeypatch):
        w, sign, acks, posts = self._worker(tmp_path, monkeypatch)
        args = {"cam": "RO000M", "date": "20260630", "filename": "x.mkv", "locked": True}
        cmd = {"id": "cmd_6", "type": "lock_clip", "args": args,
               "issued_at": _future(-1), "not_after": _future()}
        cmd["sig"] = sign(cmd, "gmn0002")
        w.handle(cmd)
        assert posts == [("/api/lock/RO000M/20260630/x.mkv", {"locked": True})]
        assert acks[-1][1] is True

    def test_run_updater_allowlisted_and_dispatches_to_run(self, tmp_path, monkeypatch):
        w, sign, acks, posts = self._worker(tmp_path, monkeypatch)
        assert "run_updater" in rp.CommandWorker.ALLOWED_TYPES
        cmd = {"id": "cmd_upd", "type": "run_updater", "args": {},
               "issued_at": _future(-1), "not_after": _future()}
        cmd["sig"] = sign(cmd, "gmn0002")
        w.handle(cmd)
        assert posts == [("/api/updater/run", None)]
        assert acks[-1][1] is True

    def test_run_updater_check_dispatches_to_check(self, tmp_path, monkeypatch):
        w, sign, acks, posts = self._worker(tmp_path, monkeypatch)
        cmd = {"id": "cmd_updc", "type": "run_updater", "args": {"check": True},
               "issued_at": _future(-1), "not_after": _future()}
        cmd["sig"] = sign(cmd, "gmn0002")
        w.handle(cmd)
        assert posts == [("/api/updater/check", None)]
        assert acks[-1][1] is True

    def test_restart_services_allowlisted_and_dispatches_to_services_restart(self, tmp_path, monkeypatch):
        w, sign, acks, posts = self._worker(tmp_path, monkeypatch)
        assert "restart_services" in rp.CommandWorker.ALLOWED_TYPES
        cmd = {"id": "cmd_svc", "type": "restart_services", "args": {},
               "issued_at": _future(-1), "not_after": _future()}
        cmd["sig"] = sign(cmd, "gmn0002")
        w.handle(cmd)
        assert posts == [("/api/services/restart", None)]
        assert acks[-1][1] is True

    def test_restart_services_connection_drop_acked_ok(self, tmp_path, monkeypatch):
        """The station_api self-restarts, so the loopback POST connection drops
        mid-response. That URLError is the success signal, not a failure."""
        w, sign, acks, _posts = self._worker(tmp_path, monkeypatch)
        # Simulate the socket reset _local_post surfaces when the API exits.
        monkeypatch.setattr(
            rp, "_local_post",
            lambda path, body=None, timeout=60: (
                False, "local action failed: <urlopen error [Errno 104] Connection reset by peer>"
            ),
        )
        cmd = {"id": "cmd_svc_drop", "type": "restart_services", "args": {},
               "issued_at": _future(-1), "not_after": _future()}
        cmd["sig"] = sign(cmd, "gmn0002")
        w.handle(cmd)
        assert acks[-1][1] is True
        assert "restart in progress" in acks[-1][2]

    def test_restart_services_http_error_still_fails(self, tmp_path, monkeypatch):
        """A real HTTP error status (not a connection drop) is still a failure."""
        w, sign, acks, _posts = self._worker(tmp_path, monkeypatch)
        monkeypatch.setattr(
            rp, "_local_post",
            lambda path, body=None, timeout=60: (False, "HTTP 500: boom"),
        )
        cmd = {"id": "cmd_svc_err", "type": "restart_services", "args": {},
               "issued_at": _future(-1), "not_after": _future()}
        cmd["sig"] = sign(cmd, "gmn0002")
        w.handle(cmd)
        assert acks[-1][1] is False
        assert "HTTP 500" in acks[-1][2]

    def test_redelivered_command_not_reexecuted(self, tmp_path, monkeypatch):
        w, sign, acks, posts = self._worker(tmp_path, monkeypatch)
        cmd = {"id": "cmd_7", "type": "reboot", "args": {},
               "issued_at": _future(-1), "not_after": _future()}
        cmd["sig"] = sign(cmd, "gmn0002")
        w.handle(cmd)
        w.handle(cmd)                            # redelivery
        assert len(posts) == 1                   # dispatched once only
        assert acks[-1][2] == "already_executed"


class TestFailClosed:
    def test_no_pubkey_returns_none(self, tmp_path, monkeypatch):
        import command_verify
        missing = tmp_path / "nope.pem"
        assert command_verify.load_public_key_raw(missing) is None
