#!/usr/bin/env bash
#
# setup_rtsp_relay.sh - install a loopback RTSP relay (MediaMTX) on a station.
#
# Why: on bandwidth-starved sites the camera ethernet links top out around
# ~10 Mbps. RMS detection and color_capture each open their own RTSP pull of
# the camera main stream (~8 Mbps CBR), so two simultaneous pulls (~16 Mbps)
# saturate the link and RMS drops frames. This relay pulls each camera ONCE and
# fans the stream out to both consumers over loopback (unmetered), so the
# camera link only ever carries a single stream.
#
#   Camera .210 --8Mbps--> 127.0.0.1:8554/cam1 --+--> rms-cam1   (loopback)
#                                                 +--> color_capture (loopback)
#
# MediaMTX does pure H.264 passthrough (no re-encode -> no CPU / quality cost)
# and reconnects automatically. sourceOnDemand means it only pulls from the
# cameras while RMS / color_capture are actually reading (zero daytime load).
#
# Idempotent: safe to re-run. Reads camera URLs from config.json. Pass
# --repoint-rms to also point the RMS per-camera .config device lines at the
# relay (backs them up first) and restart the rms-cam* services.
#
# Usage:
#   bash setup_rtsp_relay.sh [--config PATH] [--version vX.Y.Z]
#                            [--repoint-rms] [--rms-parent DIR] [--no-start]
#
set -euo pipefail

CONFIG="${HOME}/rovimen_scripts/config.json"
SCRIPTS_DIR="${HOME}/rovimen_scripts"
VERSION="v1.19.2"
BIND="127.0.0.1:8554"
REPOINT_RMS=0
RMS_PARENT="${HOME}"
NO_START=0

while [[ $# -gt 0 ]]; do
    case "$1" in
        --config)      CONFIG="$2"; shift 2 ;;
        --version)     VERSION="$2"; shift 2 ;;
        --bind)        BIND="$2"; shift 2 ;;
        --repoint-rms) REPOINT_RMS=1; shift ;;
        --rms-parent)  RMS_PARENT="$2"; shift 2 ;;
        --no-start)    NO_START=1; shift ;;
        *) echo "Unknown arg: $1" >&2; exit 2 ;;
    esac
done

BIN_DIR="${SCRIPTS_DIR}/bin"
BIN="${BIN_DIR}/mediamtx"
YAML="${SCRIPTS_DIR}/mediamtx.yml"
SERVICE_SRC="${SCRIPTS_DIR}/rovimen-rtsp-relay.service"
SERVICE_DST="/etc/systemd/system/rovimen-rtsp-relay.service"
ARCH_RAW="$(uname -m)"
case "$ARCH_RAW" in
    x86_64)  ARCH="amd64" ;;
    aarch64) ARCH="arm64v8" ;;
    armv7l)  ARCH="armv7" ;;
    *) echo "Unsupported arch: $ARCH_RAW" >&2; exit 1 ;;
esac

log() { echo "[setup_rtsp_relay] $*"; }

[[ -f "$CONFIG" ]] || { echo "Config not found: $CONFIG" >&2; exit 1; }

# --- 1. download MediaMTX binary (idempotent) -----------------------------
mkdir -p "$BIN_DIR"
if [[ -x "$BIN" ]] && "$BIN" --version 2>/dev/null | grep -q "$VERSION"; then
    log "MediaMTX $VERSION already installed at $BIN"
else
    url="https://github.com/bluenviron/mediamtx/releases/download/${VERSION}/mediamtx_${VERSION}_linux_${ARCH}.tar.gz"
    tmp="$(mktemp -d)"
    log "Downloading $url"
    curl -fsSL --retry 3 -o "$tmp/m.tgz" "$url"
    tar -xzf "$tmp/m.tgz" -C "$tmp" mediamtx
    install -m 0755 "$tmp/mediamtx" "$BIN"
    rm -rf "$tmp"
    log "Installed $("$BIN" --version 2>&1 | head -1) -> $BIN"
fi

# --- 2. generate mediamtx.yml from config.json ----------------------------
# One relay path per station with a non-empty camera_rtsp; the path name is
# derived from the camera's rms_data_path (".../cam1" -> "cam1") so it lines up
# with the RMS_cam1/.config naming. Emits the loopback capture URLs to stdout.
log "Generating $YAML from $CONFIG"
python3 - "$CONFIG" "$YAML" "$BIND" <<'PY'
import json, sys, re
config_path, yaml_path, bind = sys.argv[1], sys.argv[2], sys.argv[3]
with open(config_path) as f:
    cfg = json.load(f)

paths = {}   # relay_path -> real camera url
for sid, st in cfg.get("stations", {}).items():
    url = (st.get("camera_rtsp") or "").strip()
    if not url:
        continue
    m = re.search(r'(cam\d+)\b', st.get("rms_data_path", ""))
    name = m.group(1) if m else sid.lower()
    paths[name] = url

if not paths:
    sys.exit("No stations with a camera_rtsp found in config")

bind_host = bind.split(":")[0]   # bind everything to the same host as RTSP

lines = [
    "# Generated by setup_rtsp_relay.sh - do not edit by hand.",
    "# Loopback RTSP relay: one shared upstream pull per camera, fanned out to",
    "# RMS detection + color capture. Regenerate by re-running the setup script.",
    "logLevel: info",
    "logDestinations: [stdout]",
    "readTimeout: 20s",
    "writeTimeout: 20s",
    "api: no",
    "metrics: no",
    "pprof: no",
    "playback: no",
    "rtmp: no",
    "hls: no",
    "webrtc: no",
    "srt: no",
    "moq: no",
    "rtsp: yes",
    f"rtspAddress: {bind}",
    # Bind the RTP/RTCP UDP helper sockets to the same (loopback) host so the
    # relay exposes nothing beyond the RTSP port -- the station has no firewall.
    f"rtpAddress: {bind_host}:8000",
    f"rtcpAddress: {bind_host}:8001",
    "paths:",
]
for name in sorted(paths):
    url = paths[name]
    # MediaMTX rejects rtsp://user:@host (username present, empty password).
    # XMEye cameras carry their real credentials in the query string
    # (user=...&password=...), so an empty-password userinfo is redundant --
    # strip it so the relay's RTSP client can connect. URLs with a real
    # password (user:pass@) are left untouched.
    url = re.sub(r'^(rtsp://)[^/@]*:@', r'\1', url)
    url = url.replace('"', '\\"')
    lines += [
        f"  {name}:",
        f'    source: "{url}"',
        "    rtspTransport: tcp",
        "    sourceOnDemand: yes",
        "    sourceOnDemandStartTimeout: 10s",
        "    sourceOnDemandCloseAfter: 60s",
    ]
with open(yaml_path, "w") as f:
    f.write("\n".join(lines) + "\n")

host = bind.split(":")[0].replace("0.0.0.0", "127.0.0.1")
port = bind.split(":")[1]
print("RELAY_PATHS_START")
for name in sorted(paths):
    print(f"{name}\trtsp://{host}:{port}/{name}")
print("RELAY_PATHS_END")
PY

# --- 3. install + (re)start the systemd service ---------------------------
if [[ -f "$SERVICE_SRC" ]]; then
    tmp_unit="$(mktemp)"
    sed -e "s#/home/gmn#${HOME}#g" \
        -e "s#^User=gmn#User=$(id -un)#" \
        -e "s#^Group=gmn#Group=$(id -gn)#" \
        "$SERVICE_SRC" > "$tmp_unit"
    sudo install -m 0644 "$tmp_unit" "$SERVICE_DST"
    rm -f "$tmp_unit"
else
    echo "Service template not found: $SERVICE_SRC" >&2; exit 1
fi
sudo systemctl daemon-reload
sudo systemctl enable rovimen-rtsp-relay.service >/dev/null 2>&1 || true
if [[ "$NO_START" -eq 0 ]]; then
    sudo systemctl restart rovimen-rtsp-relay.service
    sleep 3
    if ! systemctl is-active --quiet rovimen-rtsp-relay.service; then
        echo "Relay failed to start. Recent log:" >&2
        journalctl -u rovimen-rtsp-relay.service -n 30 --no-pager >&2
        exit 1
    fi
    log "Relay active: $(systemctl is-active rovimen-rtsp-relay.service)"
fi

# --- 4. optionally repoint RMS at the relay -------------------------------
if [[ "$REPOINT_RMS" -eq 1 ]]; then
    stamp="$(date +%Y%m%d_%H%M%S)"
    host="${BIND%%:*}"; host="${host/0.0.0.0/127.0.0.1}"; port="${BIND##*:}"
    for cfgfile in "$RMS_PARENT"/RMS_cam*/.config; do
        [[ -f "$cfgfile" ]] || continue
        camdir="$(basename "$(dirname "$cfgfile")")"   # RMS_cam1
        name="${camdir#RMS_}"                          # cam1
        relay="rtsp://${host}:${port}/${name}"
        cur="$(grep -E '^device:' "$cfgfile" | head -1 | sed 's/^device:[[:space:]]*//')"
        if [[ "$cur" == "$relay" ]]; then
            log "RMS $name already points at relay"
            continue
        fi
        cp -a "$cfgfile" "${cfgfile}.bak.${stamp}"
        sed -i -E "s#^device:.*#device: ${relay}#" "$cfgfile"
        log "RMS $name device -> $relay (backup ${cfgfile}.bak.${stamp})"
        unit="rms-${name}.service"
        if systemctl list-unit-files | grep -q "^${unit}"; then
            sudo systemctl restart "$unit"
            log "Restarted $unit"
        fi
    done
fi

log "Done."
